name: dart_parquinho
description: A simple command-line application.
version: 1.0.0+2
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  dio: ^4.0.4

dev_dependencies:
  lints: ^1.0.0


